services:
  acme-cleanup:
    image: ghcr.io/aperim/traefik-acme-cleanup:latest
    volumes:
      - traefik-public-certificates:/certificates
    environment:
      - TRAEFIK_DASHBOARD_URL
      - TRAEFIK_DASHBOARD_USERNAME
      - TRAEFIK_DASHBOARD_PASSWORD
      - ACME_CLEANUP_UNUSED
      - ACME_CLEANUP_DOIT
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TRAEFIK_ACME_FILE=${TRAEFIK_ACME_FILE:-/certificates/acme.json}
      - CLEANUP_REPORT=${CLEANUP_REPORT:-/certificates/REPORT.md}
    deploy:
      mode: global
      restart_policy:
        delay: 24h

volumes:
  traefik-public-certificates:
    driver: glusterfs
    name: ${GLUSTER_PUBLIC_CERTIFICATES}
